# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('IdOsoba', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=20)),
                ('Nazwisko', models.CharField(max_length=40)),
                ('Telefon', models.IntegerField()),
                ('Mail', models.EmailField(max_length=254)),
                ('Login', models.CharField(max_length=10)),
                ('Hasło', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OsobaKontaktowa',
            fields=[
                ('pesel', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=15)),
                ('nazwisko', models.CharField(max_length=20)),
            ],
        ),
    ]
