# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbjcrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'verbose_name_plural': 'Osoba'},
        ),
        migrations.AlterModelOptions(
            name='osobakontaktowa',
            options={'verbose_name_plural': 'Osoba Kontaktowa'},
        ),
    ]
