# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbjcrm', '0002_auto_20170421_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OsobaKontaktowa',
        ),
    ]
