# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbjcrm', '0003_delete_osobakontaktowa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontrahent',
            fields=[
                ('IdKontrahent', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=50)),
                ('Opis', models.TextField()),
                ('Adres', models.TextField()),
                ('NIP', models.IntegerField()),
                ('Regon', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Kontrahent',
            },
        ),
    ]
