# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbjcrm', '0006_auto_20170421_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrahent',
            name='IdKontrahent',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='IdOsoba',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
