# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbjcrm', '0007_auto_20170421_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontrahent_Osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdKontrahent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbjcrm.Kontrahent')),
                ('IdOsoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbjcrm.Osoba')),
            ],
        ),
        migrations.CreateModel(
            name='Kontrakt',
            fields=[
                ('Nr', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('Data_zawarcia', models.DateField()),
                ('Data_platnosci_fizycznej', models.DateField()),
                ('Kontrahent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbjcrm.Kontrahent')),
            ],
            options={
                'verbose_name_plural': 'Kontrakt',
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('IdProduktu', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Produkt',
            },
        ),
        migrations.AddField(
            model_name='kontrakt',
            name='Produkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbjcrm.Produkt'),
        ),
    ]
