# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbjcrm', '0008_auto_20170421_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kontrahent_osoba',
            options={'verbose_name_plural': 'Kontrahent-Osoba'},
        ),
    ]
