# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbjcrm', '0009_auto_20170421_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rola',
            fields=[
                ('Rola', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Rola',
            },
        ),
    ]
