# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbjcrm', '0010_rola'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrakt',
            name='Kwota_oplaty_licencyjnej',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kontrakt',
            name='RCP',
            field=models.CharField(default='', max_length=30),
        ),
    ]
