# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbjcrm', '0013_auto_20170421_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naleznosc',
            fields=[
                ('IDNaleznosc', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('Data', models.DateField()),
                ('Tytul', models.CharField(blank=True, max_length=50, null=True)),
                ('Kwota', models.IntegerField(default=0)),
                ('Zrealizowane', models.BooleanField()),
                ('IDKonta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbjcrm.Kontrakt')),
            ],
            options={
                'verbose_name_plural': 'Należność',
            },
        ),
        migrations.AlterField(
            model_name='kontrahent',
            name='Adres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kontrahent',
            name='Opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kontrahent',
            name='Regon',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='Hasło',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='Login',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='Mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='Telefon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
