# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbjcrm', '0015_auto_20170424_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naleznosc',
            old_name='IDKonta',
            new_name='IDKontrakt',
        ),
    ]
