# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbjcrm', '0017_auto_20170425_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='naleznosc',
            name='Kopia',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
